#!/usr/bin/env bash
# PreToolUse hook: block any file write/edit targeting the generated/ directory.
#
# Uses the current hookSpecificOutput API (top-level decision/reason is deprecated
# for PreToolUse as of Claude Code v2.1.x).
#
# Exit 0 with JSON on stdout → Claude Code reads the decision.
# Exit 2 → also blocks, but gives Claude no structured reason. Use JSON instead.

set -euo pipefail

INPUT=$(cat)
TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // empty')

# Only inspect file-writing tools
if [[ ! "$TOOL_NAME" =~ ^(Write|Edit|MultiEdit)$ ]]; then
    exit 0
fi

FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

# MultiEdit carries file_path inside each edit entry; check the top-level path.
# If the tool is MultiEdit and file_path is absent at top level, check edits[].
if [[ -z "$FILE_PATH" && "$TOOL_NAME" == "MultiEdit" ]]; then
    FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.edits[0].file_path // empty')
fi

if [[ -z "$FILE_PATH" ]]; then
    exit 0
fi

# Resolve to an absolute path for reliable prefix matching
ABS_PATH=$(realpath -m "$FILE_PATH" 2>/dev/null || echo "$FILE_PATH")
CWD=$(echo "$INPUT" | jq -r '.cwd // empty')

# Match any path that contains /generated/ or ends in /generated
# Works whether the project root is absolute or relative
if echo "$ABS_PATH" | grep -qE '(^|/)(generated)(/|$)'; then
    jq -n \
        --arg reason "Write to generated/ is blocked. This directory is regenerated by the build system. Edit the source template or generator instead, then rebuild." \
        '{
            hookSpecificOutput: {
                hookEventName: "PreToolUse",
                permissionDecision: "deny",
                permissionDecisionReason: $reason
            }
        }'
    exit 0
fi

exit 0
